name: BatchDLLHijacker

on:
  schedule:
    - cron: '0 */20 * * *'  # 每20小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  scan:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'

        
    - name: start
      env:
        PYTHONUNBUFFERED: 1
      run: |
        pip install requests
        python main.py
        python unzip.py
        .\ZeroEye.exe -s -nc -p download
        python zip.py


    - name: Upload the result file as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: result-file
        path: |
          Eyebin.zip
        retention-days: 3
