name: clone scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


        
    - name: start
      env:
        PYTHONUNBUFFERED: 1
      run: |
        python main.py
        zip -r ../result.zip ./download/


    - name: Upload the result file as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: result-file
        path: |
          result.zip
